### ISSUE TITLE
PyLNP: No such file or directory at startup

### ISSUE THREAD

**Issue by kusayuzayushko** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#10]
./startlnp  
LNP/utilities/dwarf_therapist/DwarfTherapist (No such file or directory)
./startlnp: line 15: ./PyLNP: No such file or directory

**Comment by lethosor** [comment]
Do those files exist? Where did you download your copy of the pack?

**Comment by kusayuzayushko** [comment]
$ git pull
Already up-to-date.

$ pwd
/home/kusayu/Games/Lazy-Newb-Pack-Linux

$ls pack/ | grep PyLNP
PyLNP.json

$ ls pack/LNP/utilities
exclude.txt  include.txt  README.md

> Do those files exist?

It seems not.

> Where did you download your copy of the pack?

Get it via 'git clone https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux'

Also, if I use the pack taken out of the DFFD, there have these files, but i have en error 'Tileset not Found. Not found: data/art/Phoebus_16x16.png'

**Comment by lethosor** [comment]
This repo does not include binaries at all. You should download a full package from the "releases" tab in this repo or from DFFD. Since it sounds like you've done that, what distro are you using? Do you see any messages that start with "[distro_fixes]" in the terminal?

(Edit: You can also download the pack from http://lazynewbpack.com/)

**Comment by kusayuzayushko** [comment]
Yes, there are such messages
[distro_fixes] INFO Checking whether any ARCH/distro specific fixes are required...
[distro_fixes] INFO OS: Linux
[distro_fixes] INFO ARCH: x86_64
[distro_fixes] INFO VER: 4.0.1-1-ARCH
[distro_fixes] INFO DF_ARCH: 32-bit
[distro_fixes] INFO DF_BIN_LOCATION: /home/kusayu/Games/04024r3-x64/df_linux/libs/Dwarf_Fortress
[distro_fixes] INFO 32 bit df on Linux/64bit detected
[distro_fixes] WARN 32bit 'Dwarf_Fortress' on unhandled 64bit OS detected. If you get 'missing file' errors, please open an issue on Github: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues.
[distro_fixes] INFO Done

a have a 64bit ArchLinux machine, and there are many tiles fies in '../04024r3-x64/df_linux/data/art/'
What i'm doing wrong?

**Comment by lethosor** [comment]
Can you try replacing distro_fixes.sh with the [latest version](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/df_linux/distro_fixes.sh) ([raw link](https://raw.githubusercontent.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/master/pack/df_linux/distro_fixes.sh))?

**Comment by lethosor** [comment]
A couple other questions:
- What's the output of `lsb_release -si`?
- What are the contents of `/etc/os-release`?

**Comment by kusayuzayushko** [comment]
Same problem with new distro_fixes.sh

[distro_fixes] [INFO] Checking whether any distro specific fixes are required...
which: invalid option -- 's'
[distro_fixes] [INFO] OS: antergos
[distro_fixes] [INFO] ARCH: x86_64
[distro_fixes] [INFO] VER: 
[distro_fixes] [INFO] DF_ARCH: /usr/bin/egrep
32-bit
[distro_fixes] [INFO] DF_BIN_LOCATION: /home/kusayu/Games/04024r3-x64/df_linux/libs/Dwarf_Fortress
[distro_fixes] [INFO] PRELOAD_LIB: 
[distro_fixes] [INFO] LD_LIBRARY_PATH: /tmp/_MEIZzObsA
[distro_fixes] [INFO] Done

and, yes, antergos is  a Arch based distro. I totally forgot about it, sorry for that.

> lsb_release -si

Arch

> cat /etc/os-release

NAME=Antergos
ID=antergos
ID_LIKE=arch
PRETTY_NAME=Antergos
ANSI_COLOR="1;34;40"
HOME_URL="http://www.antergos.com/"
SUPPORT_URL="http://forum.antergos.com/"
BUG_REPORT_URL="http://bugs.antergos.com/"

**Comment by lethosor** [comment]
All right, can you try distro_fixes from [this branch](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/antergos-fixes/pack/df_linux/distro_fixes.sh)?

**Comment by kusayuzayushko** [comment]
Finally! It work, i am very  appreciate for your help.
Also, I saw it in the log

...
Can't load plugin /home/kusayu/Games/04024r3-x64/df_linux/hack/plugins/stonesense.plug.so
...
is it ok?

and here is distro_fixes log
[distro_fixes] [INFO] Checking whether any distro specific fixes are required...
[distro_fixes] [INFO] OS: arch
[distro_fixes] [INFO] ARCH: x86_64
[distro_fixes] [INFO] VER: rolling
[distro_fixes] [INFO] DF_ARCH: 32-bit
[distro_fixes] [INFO] DF_BIN_LOCATION: /home/kusayu/Games/04024r3-x64/df_linux/libs/Dwarf_Fortress
[distro_fixes] [INFO] 32 bit df on arch/64bit detected
[distro_fixes] [INFO] Attempting to use zlib at /usr/lib32/libz.so
[distro_fixes] [INFO] PRELOAD_LIB: /usr/lib32/libstdc++.so.6:/usr/lib32/libz.so
[distro_fixes] [INFO] LD_LIBRARY_PATH: /tmp/_MEIa478fR
[distro_fixes] [INFO] Done

**Comment by lethosor** [comment]
Good to hear! Regarding Stonesense, you're probably missing the right version of libjpeg or some other dependencies - check stderr.log in the DF folder for details.

**Comment by ri0t** [comment]
Running Debian unstable here, getting same results. The release tarball here doesn't contain pyLNP nor the Therapist.

**Comment by lethosor** [comment]
If you're downloading a tarball, that's generated by Github and equivalent to cloning the repo, which won't give you a working pack. You want "04024r3-x64.zip" or "04024r3-i686.zip" (follow the links to the legacy repo if you're looking at this repo's releases page).
