### ISSUE TITLE
Keybinds have no option to cycle automining veins/ores setting.

### ISSUE THREAD

**Issue by yankee14** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#11]
The dig designation menu has no keybind available for changing between 'Designate all' for mining and 'automine vein'.  The setting is available and functions properly in vanilla df linux with the default key set to 'a', but none of the keybinds files in LNP have any effect on this particular keybind.  I tested with all the keybinds available in LNP, and tried several different graphics packs to see if that had any effect:  no change.  Dwarf Fortress only shows a question mark for the key combo.

I also can't seem to find the line in the keybinds file that references the automining function.

Format: ![See image](https://i.imgur.com/7WqxeJn.png)
Relevant discussion on reddit: https://www.reddit.com/r/dwarffortress/comments/36077y/biweekly_df_questions_thread/crbgqx9

**Comment by lethosor** [comment]
Well, they're listed [here](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/df_linux/data/init/interface.txt#L2121-L2126). @BeauBouchard are there other keybinding files included in the LNP that aren't in this repo?

> I also can't seem to find the line in the keybinds file that references the automining function.

That would be because it's missing, most likely due to the keybinding file being outdated.

**Comment by yankee14** [comment]
@lethosor Thanks for linking me to that [interface.txt](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/df_linux/data/init/interface.txt#L2121-L2126).  I added those lines, changed the fortification designation command from 'a' to 'f', and all seems to be working well.  Excited to try out the automining feature.  I'd commit the changes I made here, but I don't know who is in charge of setting key combos or even how to do much more than a git clone.

Anyways, thanks for your help.  I guess this ticket can stay open because technically the problem still exists in this repo.

**Comment by lethosor** [comment]
I checked @PeridexisErrant's keybinding file in this repo and in [LNP-shared-core](https://github.com/Lazy-Newb-Pack/LNP-shared-core/blob/master/LNP/keybinds/PeridexisErrant.txt) and the latter is up-to-date. @BeauBouchard since the LNP folder in this repo contains many of the same files as LNP-shared-core, would it be all right to set that up as a submodule?

**Comment by lethosor** [comment]
@Yankee14 I replaced the pack/LNP folder in this repo with a submodule pointing to the LNP-shared-core repo. All keybinding files in it were up-to-date, and I updated New_LNP.txt manually. You could try downloading an [archive](https://github.com/Lazy-Newb-Pack/LNP-shared-core/archive/master.zip) of the LNP-shared-core repo and copying over the "keybinds" folder from it over the "keybinds" folder in your pack.

**Comment by yankee14** [comment]
@lethosor Thanks again.  Should I go ahead and close this ticket?

For posterity:  Just for the heck of it, I did a diff -u on the Vanilla_DF.txt between my LNP and the archive you gave me to check some of the fundamental differences I could expect across all the keybinds files.  There are only 3 or so changes:
1.  Added the new do-task-now feature key at workshops.
2.  Changed create fortification designation.
3.  Added the new mining mode/marker designation which is the original subject of this bug report.

```
--- 04024r3-x64/LNP/keybinds/Vanilla_DF.txt     2015-02-08 13:03:22.000000000 -0600
+++ LNP-shared-core-master/keybinds/Vanilla_DF.txt      2015-05-20 16:51:32.000000000 -0500
@@ -1567,6 +1567,8 @@
 [KEY:c]^M
 [BIND:BUILDJOB_PROMOTE:REPEAT_NOT]^M
 [KEY:p]^M
+[BIND:BUILDJOB_NOW:REPEAT_NOT]^M
+[KEY:n]^M
 [BIND:BUILDJOB_REPEAT:REPEAT_NOT]^M
 [KEY:r]^M
 [BIND:BUILDJOB_SUSPEND:REPEAT_NOT]^M
@@ -2111,11 +2113,17 @@
 [BIND:DESIGNATE_ENGRAVE:REPEAT_NOT]^M
 [KEY:e]^M
 [BIND:DESIGNATE_FORTIFY:REPEAT_NOT]^M
-[KEY:a]^M
+[KEY:F]^M
 [BIND:DESIGNATE_TRACK:REPEAT_NOT]^M
 [KEY:T]^M
 [BIND:DESIGNATE_TOGGLE_ENGRAVING:REPEAT_NOT]^M
 [KEY:v]^M
+[BIND:DESIGNATE_TOGGLE_MARKER:REPEAT_NOT]^M
+[KEY:M]^M
+[BIND:DESIGNATE_STANDARD_MARKER:REPEAT_NOT]^M
+[KEY:m]^M
+[BIND:DESIGNATE_MINE_MODE:REPEAT_NOT]^M
+[KEY:a]^M
 [BIND:DESIGNATE_UNDO:REPEAT_NOT]^M
 [KEY:x]^M
 [BIND:DESIGNATE_REMOVE_CONSTRUCTION:REPEAT_NOT]^M
(END)

```

**Comment by yankee14** [comment]
The archived LNP-shared-core keybinds fixed the issue with automining, but changed other (really important) keybinds:  for example, I liked that '=' was used to cycle the menu item selection cursor down, instead of change to '+' in LNP-shared-core.  If the change is really what the author wanted, then fine, but I chose this keybind specifically because it was the only one that behaved in a sensible way for me on a laptop.

**Comment by lethosor** [comment]
Which file are you referring to? There are four keybinding files in the [keybinds](https://github.com/Lazy-Newb-Pack/LNP-shared-core/tree/master/keybinds) folder.
Edit: PeridexisErrant.txt has the binding you mentioned. In any case, it's very easy to change manually (esc -> keybindings -> general).

**Comment by yankee14** [comment]
@lethosor [Classic_LNP.txt](https://github.com/Lazy-Newb-Pack/LNP-shared-core/blob/master/keybinds/Classic_LNP.txt), which has the [following description](https://github.com/Lazy-Newb-Pack/LNP-shared-core#lnpkeybinds):

> ... The Classic LNP keybinds are adapted for laptop keyboards...

Edit: Okay, thanks.
