### ISSUE TITLE
Some df issues

### ISSUE THREAD

**Issue by Bakita** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#12]
After all, i have ubuntu gnome 15.04, 64bits 
when i start ./df i get 
[distro_fixes] [WARN] 32bit 'Dwarf_Fortress' on unhandled 64bit OS detected.
this only with the github files

this warnings show up in both version(with and withow github files)
also many (Dwarf_Fortress:21295): Gtk-WARNING *_: Imposible encontrar el motor de temas en la ruta al _modulo: «pixmap» and (Dwarf_Fortress:21295): Gtk-WARNING *_: Imposible encontrar el motor de temas en la ruta al _modulo: «pixmap»,
finally.  Gtk-Message: Failed to load module "canberra-gtk-module"

sorry for my bad english, :)

**Comment by lethosor** [comment]
What's the full output of distro_fixes.sh? (e.g. `[INFO] OS: ...`, `[INFO] ARCH: ...`, etc.)

**Comment by lethosor** [comment]
This should be fixable by replacing distro_fixes.sh with [the latest version](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/df_linux/distro_fixes.sh). If that doesn't help, feel free to reopen this issue.
