### ISSUE TITLE
Missing tilesets on OpenSuse 13.1 64bit

### ISSUE THREAD

**Issue by dizzyk** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#15]
Well, just like the previous issue, so I just edited distro_fixes.sh:

<code>
     elif [ x"$OS" == x'openSUSE project' ]; then
         export PRELOAD_LIB="${PRELOAD_LIB:+$PRELOAD_LIB:}/usr/lib/libz.so";
         dlog "INFO" "32 bit df on $OS/64bit detected. Will set LD_PRELOAD to $PRELOAD_LIB...."  
</code>

and works just fine :)

**Comment by linuxrecon** [comment]
I can confirm that this is also working under openSUSE 13.2 64-Bit.

Should we commit a patch or is this way of an announcement enough?

**Comment by lethosor** [comment]
I'm pretty sure this has already been added.

**Comment by lethosor** [comment]
Yeah, in d467d88. (The library should still be found if it's in /usr/lib; the arguments to find_zlib only prioritize certain paths.)
