### ISSUE TITLE
more consistent distro detection

### ISSUE THREAD

**Issue by daxim** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#17]
prefer [`/etc/os-release`](http://www.freedesktop.org/software/systemd/man/os-release.html) over `uname` and `lsb_release`

**Comment by lethosor** [comment]
This is also done in master: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/e5d725ac4f5ac7c0e3bb24e83aac3120feebec77/pack/df_linux/distro_fixes.sh#L85-L87 (well, os-release isn't preferred over lsb_release or fedora-release, but it is recognized - I'm not sure why os-release would be preferable, but it's fine to change it if there's a reason I'm not aware of). You can click the "Raw" button and update your copy of the script if you like.

(@BeauBouchard, another pack release would be much appreciated.)
