### ISSUE TITLE
Arch Linux x64 Not found error

### ISSUE THREAD

**Issue by hexmaster111** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#19]
When trying to start the game I get "Not found: data/art/Phoebus_16x16.png" and looking at the term output it says that if i have a missing file error report it here.

**Comment by lethosor** [comment]
Try replacing distro_fixes.sh in the DF folder with https://raw.githubusercontent.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/master/pack/df_linux/distro_fixes.sh

**Comment by hexmaster111** [comment]
perfect, Thanks working grate

**Comment by lethosor** [comment]
This should be fixed in the next release, so I'm closing this for now.

**Comment by jeaye** [comment]
I'm seeing this issue with the http://lazynewbpack.com/linux/04024/download/x64/04024r3-x64.zip release. Is the next release not yet out?

**Comment by lethosor** [comment]
Unfortunately not (@BeauBouchard is the one who does releases). You'll have to update distro_fixes.sh on your own for now.
