### ISSUE TITLE
xdg-terminal: configured terminal program '' not found or not executable

### ISSUE THREAD

**Issue by mikebell** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#2]
Running Ubuntu 14.04 with zsh

digital@digital-ubuntu [11:11:59] [~/04024r2-x64] 
-> % ./startlnp 
xdg-terminal: configured terminal program '' not found or not executable

PyLNP gui starts but that's the output when I press "Play Drawf Fortress". Running df_linux/dfhack works fine.

**Comment by lethosor** [comment]
Looks like https://github.com/Lazy-Newb-Pack/LNP-Linux-legacy/issues/12 (there are some suggestions in later comments). If that doesn't help, what terminal emulator are you using?

**Comment by mikebell** [comment]
When I run:

```
$ gconftool-2  --get /desktop/gnome/applications/terminal/exec
```

Nothing is returned

Setting:

```
$ gconftool-2 --type string --set /desktop/gnome/applications/terminal/exec gnome-terminal
```

Works fine.
