### ISSUE TITLE
x64 linux: line 11: ./libs/Dwarf_Fortress : not found

### ISSUE THREAD

**Issue by kaos-addict** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#22]
Hi,
I'm currently running Kaos Linux whitch is a x64 only distrib and whitch _could be compared to_ an arch linux system.
After few modifications[*](#note), I get this when running df from command-line with `./df` and same response with: `./dfhach` (and running with `bash -x` doesn't give any clue more):

```
[distro_fixes] [INFO] Checking whether any distro specific fixes are required...
[distro_fixes] [INFO] OS: kaos
[distro_fixes] [INFO] ARCH: x86_64
[distro_fixes] [INFO] VER: rolling
[distro_fixes] [INFO] DF_ARCH: 32-bit
[distro_fixes] [INFO] DF_BIN_LOCATION: /home/mermouy/apps/04024r3-x64/df_linux/libs/Dwarf_Fortress
[distro_fixes] [INFO] 32 bit df on kaos/64bit detected
[distro_fixes] [WARN] 32bit 'Dwarf_Fortress' on unhandled 64bit OS detected. If you get 'missing file' errors, please open an issue on Github: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues.
[distro_fixes] [INFO] Attempting to use zlib at /usr/lib/libz.so
[distro_fixes] [INFO] PRELOAD_LIB: /usr/lib/libz.so
[distro_fixes] [INFO] LD_LIBRARY_PATH: 
[distro_fixes] [INFO] Done
./df: ligne 11: ./libs/Dwarf_Fortress: Aucun fichier ou dossier de ce type
```

Witch make me wonder is it normal that it gives: `LD_LIBRARY_PATH:` ?

<a name="note">*</a>: I Have:
-  applied last distro_fixes.sh [as mentioned here](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues/19)
-  Created a symbolic link like: `ln -s /usr/bin/kreadconfig5 /usr/bin/kreadconfig`, as Kaos is running complete and only kf5 desktop, there's is no more kreadconfig executable (that should be an issue by itself? Should I create it?)

**Comment by kaos-addict** [comment]
I just realized that df is 32bit only... Maybe my issue is just stupid as Kaos as no multilib support...?

**Comment by lethosor** [comment]
Yeah, you need to be able to run 32-bit executables and use 32-bit libraries. Toady's working on a 64-bit build, but it won't be available until after the next release.

**Comment by kaos-addict** [comment]
Nice thank you:
