### ISSUE TITLE
How to start stonesense?

### ISSUE THREAD

**Issue by MaximilianKindshofer** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#24]
Hi - I am on Archlinux 64 bit and Iam starting LNP via ./PyLNP in my console.

I tried to start stonesense for my fortress and dfhack replies:

[DFHack]# stonesense
stonesense is not a recognized command.

I am not sure how to invoke stonesense - I thought this would be the right way.

**Comment by lethosor** [comment]
Does a line similar to "Can't load plugin: stonesense" appear in the DFHack console? If so, check stderr.log for more details - you probably need to install a 32-bit libjpeg.

**Comment by MaximilianKindshofer** [comment]
Ok I looked in the wrong sterr.log - the log in the df_linux folder told me:

Can't load plugin /home/maximilian/Downloads/04024r3-x64/df_linux/hack/plugins/stonesense.plug.so

stderr tells me:

libpng12.so.0: cannot open shared object file: No such file or directory

I have:

1 extra/libpng 1.6.18-1 [installed]
    A collection of routines used to create PNG format graphics files
2 multilib/lib32-libpng 1.6.18-1 [installed]
    A collection of routines used to create PNG format graphics files (32-bit)

installed, but it turns out that it is a diffrent library: https://bbs.archlinux.org/viewtopic.php?id=89987

I installed libpng12

So I checked for jpeg support

1 extra/libjpeg-turbo 1.4.2-1 [installed]
    JPEG image codec with accelerated baseline compression and decompression
2 multilib/lib32-libjpeg-turbo 1.4.2-1 [installed]
    libjpeg derivative with accelerated baseline JPEG compression and 
    decompression (32-bit)

Yep you guess it - the wrong jpeg libs... I in fact needed:

jpeg6-turbo

So thanks for guiding me there - I will make a post to the archwiki
