### ISSUE TITLE
Tileset Not found (Arch x64)

### ISSUE THREAD

**Issue by bashterm** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#25]
When running dwarf fortress from PyLNP using default settings I get an error window stating "Not found: data/art/Phoebus_16x16.png". I have tried fixes found on other (closed) threads, and none of them have worked. This is a completely fresh install. Thanks for any help you can supply!

**Comment by lethosor** [comment]
Try replacing distro_fixes.sh with https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/df_linux/distro_fixes.sh

**Comment by bashterm** [comment]
That did the trick. Thank you so much!

**Comment by lethosor** [comment]
Should be fixed in the next release, then (@BeauBouchard)

**Comment by alextes** [comment]
Just ran into this as well. Thanks for the fix!

**Comment by florian-s-code** [comment]
Thanks for the fix ! But I confirm this is still needed for Archlinux x64. Maybe this should be put somewhere easily seen.

**Comment by lethosor** [comment]
It should be in the next release, but BeauBouchard hasn't been around to make a release in a while.
