### ISSUE TITLE
Arch Linux distro fix not working

### ISSUE THREAD

**Issue by Wiki-fan** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#29]
I still get "missing files" errors. It says so:
`[distro_fixes] INFO Checking whether any ARCH/distro specific fixes are required...`
`[distro_fixes] INFO OS: Linux`
`[distro_fixes] INFO ARCH: x86_64`
`[distro_fixes] INFO VER: 4.3.3-3-ARCH`
`[distro_fixes] INFO DF_ARCH: 32-bit`
`[distro_fixes] INFO 32 bit df on Linux/64bit detected`
`[distro_fixes] WARN 32bit 'Dwarf_Fortress' on unhandled 64bit OS detected. If you get 'missing file' errors, please open an issue on Github: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues.`
`[distro_fixes] INFO Done`
It looks like OS variable is just `Linux`. 
If I simply change `elif [ x"$OS" == x'Arch' ]; then` to `elif [ x"$OS" == x'Linux' ]; then`, everything works.

**Comment by blotta** [comment]
I have the exact same output. 
Sorry, but what file should be changed?

**Comment by Wiki-fan** [comment]
It is quite dirty trick, but changing `distro_fixes.sh` can be a temporary solution.

**Comment by blotta** [comment]
My god! Dirty did it! Thanks!

**Comment by lethosor** [comment]
Can you try replacing that file with the latest version in this repo?

**Comment by blotta** [comment]
Copying the file  `distro_fixes.sh` from this repo to the DF downloaded from [lazy newb pack linux](http://lazynewbpack.com/linux/) also did the trick! Thanks

**Comment by Wiki-fan** [comment]
Yes, it works. But why stuff on [http://lazynewbpack.com/linux/](http://lazynewbpack.com/linux/) so outdated?
Anyway, thx. Problem is solved.
