### ISSUE TITLE
Receiving error with missing terminal settings

### ISSUE THREAD

**Issue by Nimmo** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#31]
Whenever I attempt to run Dwarf Fortress I get the following errors:
`No value set for '/desktop/gnome/applications/terminal/exec'
No value set for '/desktop/gnome/applications/terminal/exec_arg'
xdg-terminal: configured terminal program '' not found or not executable`

I have confirmed that I have set exec and exec_arg for both gnome and cinnamon, the DE which I actually use, but LNP fails to start from either DE.

Any advice that could be offered would be appreciated and any other information will be gladly offered.

**Comment by Nimmo** [comment]
Looks like my issue was that I was running the wrong program to set the default emulator.
I ran:
`gconftool-2 --type string --set /desktop/gnome/applications/terminal/exec terminator` instead and I'm now getting past that problem. 

It's still not starting, but that's another issue I will start investigating now. Apologies for the false report.

**Comment by lethosor** [comment]
You could try updating distro_fixes.sh with the latest copy from this repo (in pack/df_linux).

**Comment by Nimmo** [comment]
I think the problem was that I was trying to run it on a netbook which only has 2gb ram. It ran on my laptop which has the same packages installed.

**Comment by lethosor** [comment]
DF doesn't require a specific amount of memory to start.
