### ISSUE TITLE
Tileset not found

### ISSUE THREAD

**Issue by kabads** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#37]
`Not found: data/art/Phoebus_16x16.png`
This is after running dfhack from the command line. I initially tried running PyNLP but nothing seemed to work, so I thought I would backtrack to see the problem. This is with version 04024r3-x64 on Arch Linux. 

[edit] oh and I checked if the file was there, and it is.

**Comment by lethosor** [comment]
#25, #19, maybe?

**Comment by kabads** [comment]
#25 fixed it - thanks for that.
