### ISSUE TITLE
Tileset not found

### ISSUE THREAD

**Issue by MaximilianKindshofer** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#42]
[distro_fixes] INFO VER: 4.6.4-1-ARCH
[distro_fixes] INFO DF_ARCH: 32-bit
[distro_fixes] INFO DF_BIN_LOCATION: /home/maximilian/Downloads/lnp/04024r3-x64/df_linux/libs/Dwarf_Fortress
[distro_fixes] INFO 32 bit df on Linux/64bit detected
[distro_fixes] WARN 32bit 'Dwarf_Fortress' on unhandled 64bit OS detected. If you get 'missing file' errors, please open an issue on Github: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues.
[distro_fixes] INFO Done

Tileset not found

Not found: data/art/Phoebus_16x16.png

**Comment by MaximilianKindshofer** [comment]
Must be a duplicate of https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues/25
I fixed it with the mentioned distro_fix script

**Comment by lethosor** [comment]
Yeah, that's a common issue with the 0.40.24 pack. You could try [this one](http://www.bay12forums.com/smf/index.php?topic=156011.0) instead if you'd like to play a newer version.
