### ISSUE TITLE
DF failed to start in Ubuntu

### ISSUE THREAD

**Issue by foundoulis** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#43]
`[distro_fixes] [INFO] Checking whether any distro specific fixes are required...
[distro_fixes] [INFO] OS: ubuntu
[distro_fixes] [INFO] ARCH: x86_64
[distro_fixes] [INFO] VER: 16.10
[distro_fixes] [INFO] DF_ARCH: 32-bit
[distro_fixes] [INFO] DF_BIN_LOCATION: /home/derek/DwarfFortress/df_linux/libs/Dwarf_Fortress
[distro_fixes] [INFO] 32 bit df on ubuntu/64bit detected
[distro_fixes] [WARN] 32bit 'Dwarf_Fortress' on unhandled 64bit OS detected. If you get 'missing file' errors, please open an issue on Github: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues.
[distro_fixes] [WARN] Could not find a 32-bit zlib
[distro_fixes] [INFO] PRELOAD_LIB: 
[distro_fixes] [INFO] LD_LIBRARY_PATH: /tmp/_MEIJUy8ix
[distro_fixes] [INFO] Done
./libs/Dwarf_Fortress: error while loading shared libraries: libSDL-1.2.so.0: cannot open shared object file: No such file or directory
`

This error shows when I try to run dwarf fortress.

**Comment by CMarten** [comment]
I had the same error, this fixed it for me:

http://dwarffortresswiki.org/index.php/DF2014:Installation#64bit
