### ISSUE TITLE
TWBT: data/art/white1px.png not found, can not continue

### ISSUE THREAD

**Issue by mpicard** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#50]
Using LinuxLNP-0.43.05-r7 with Spacefox and TWBT multilevel I  receive the following errors:
```
[distro_fixes] [INFO] Checking whether any distro specific fixes are required...
[distro_fixes] [INFO] OS: ubuntu
[distro_fixes] [INFO] ARCH: x86_64
[distro_fixes] [INFO] VER: 16.04
[distro_fixes] [INFO] DF_ARCH: 64-bit
[distro_fixes] [INFO] DF_BIN_LOCATION: /home/martin/LNP/df_linux/libs/Dwarf_Fortress
[distro_fixes] [INFO] PRELOAD_LIB: 
[distro_fixes] [INFO] LD_LIBRARY_PATH: 
[distro_fixes] [INFO] Done
Loading bindings from data/init/interface.txt
Resetting textures
TWBT: version 6.22
TWBT: no display patch (not an error)
TWBT: data/art/white1px.png not found, can not continue
Plugin twbt has failed to initialize properly.
multilevel is not a recognized command.
DFHack is ready. Have a nice day!
DFHack version 0.43.05-r3 (release) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.
```
This version of the pack doesn't seem to have `white1px.png` in any of the `data/art` folders, with a bit of googling I found the files in TWBT repo but adding them still didn't fix the issue, same message.  Any help here? (I also tried the instructions found [here](http://dwarffortresswiki.org/index.php/DF2014:Installation#.22Not_found:_.2Fdata.2Fart.2Fmouse.png.22_and_similar_errors) to no avail)

**Comment by lethosor** [comment]
Those were all the things I was going to suggest, so I'm not sure what's wrong if none of them worked. There might be more people that check the forum thread for whatever pack you're using.

**Comment by mpicard** [comment]
I figured it out!!! It’s not the graphics/__tileset__/data/art it’s the
df_linux/data/art that’s missing the white1px.png and transparent.png!
Someone might want to update the repo to include those because newer
versions of TWBT (around 6.23+ or something) added it. It fixed all the
artifacts and broken tiles for me!!

**Comment by carterscottm** [comment]
I just pushed a commit that added these files to the LNP/tilesets dir.  These files get added to df_linux/data/art at first launch of PyLNP and when graphics packs are changed.

**Comment by mpicard** [comment]
Awesome 👏🏻
