### ISSUE TITLE
Could not find a 64-bit zlib

### ISSUE THREAD

**Issue by bezerradev** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#52]
How solve?
**S.O:** Ubuntu 16.04 LTS
**LNP Version:** LinuxLNP-0.44.05-r02

> [distro_fixes] [WARN] 64bit 'Dwarf Fortress' on unhandled 64bit OS detected. If you get 'missing file' errors, please open an issue on Github: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues.
> [distro_fixes] [WARN] Could not find a 64-bit zlib

**Comment by lethosor** [comment]
Does DF still work? That script is supposed to help fix issues on 32-bit systems, so if it works despite the warning (on any system), you should be fine.

**Comment by ohexel** [comment]
Does adding `/lib/x86_64-linux-gnu` to the paths that `find_zlib()` searches (line 26 in `distro_fixes.sh`) help?

**Comment by gumpu** [comment]
Had the same problem. Adding /lib/x86_64-linux-gnu resolved the problem.

(Am on Ubuntu 16.04.3 LTS / LinuxLNP-0.44.09-r01 )

**Comment by lethosor** [comment]
Is it actually a problem, though? Was it keeping DF from launching?

**Comment by ohexel** [comment]
No. DF still launches fine for me. I tested reveal/unreveal in fortress mode, seemed fine.

**Comment by gumpu** [comment]
Same here. DF launches.  (However I don't get stonesense to work, but it now fails at a different library).

**Comment by ohexel** [comment]
Yup, stonesense, 3dveins, and rendermax don't load for me, but I haven't dug in yet to figure out why.

**Comment by lethosor** [comment]
Can you post your stderr.log? 3dveins doesn't use anything special.

**Comment by ohexel** [comment]
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/ole/Downloads/LinuxLNP-0.44.09-r01/df_linux/hack/plugins/3dveins.plug.so)
    Can't load plugin 3dveins

[stderr.log](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/files/1938576/stderr.log)

**Comment by lethosor** [comment]
Huh, that's a new one. Are you using the GCC 7 or 4.8 build of DFHack?

**Comment by ohexel** [comment]
I'm not sure. The one packaged w the LinuxLNP, v0.44.09-r01.

**Comment by lethosor** [comment]
It might be an issue with both, actually, if it's a glibc issue. I'll see if there's a way to get it to link against an older glibc.

**Comment by gumpu** [comment]
Have the same message in my stderr.log.   According to ldd the glibc on Ubuntu 16.04.4 is 
GLIBC 2.23-0ubuntu10.

**Comment by BenLubar** [comment]
The next version of DFHack will have the GCC 4.8 builds made on Ubuntu Trusty (from 2014), so this issue should go away at that point.

**Comment by Zth--** [comment]
I'm having this problem and DF won't launch (it was working fine last night), I guess i'll stick to an older version

**Comment by carterscottm** [comment]
Fixed in 7412b87
