### ISSUE TITLE
Missing data/art/shadows.png in pack 0.44.12-r01

### ISSUE THREAD

**Issue by daniel-ferguson** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#60]
Pack version: 0.44.12-r01
Found at: http://dffd.bay12games.com/file.php?id=13244

---

Hi, I'm not sure if this is the right place to report issues with specific pack releases, if not feel free to close.

With TWBT Multi-level enabled in the DFHack tab of PyLNP, when I start dwarf fortress I see this error in the DFHack terminal window:

```
TWBT: data/art/shadows.png not found, shadows will not be rendered
```

It looks like that file *is* present in the pack but as `data/twbt_art/shadows.png`. It's possible that I've missed a step somewhere to get LNP to copy that file over, or change the path TWBT looks for assets in.

After manually copying the file over all is fine.

**Comment by carterscottm** [comment]
Thank you for the report, I'll get this patched up when I return from vacation next week.

**Comment by lethosor** [comment]
For reference, this is probably one that could just be copied into data/art unconditionally - it won't affect anything if TWBT isn't enabled.

**Comment by carterscottm** [comment]
My build script is configured to copy all the png files from the twbt plugin to data/art.  This will no longer be an issue moving forward.
