### ISSUE TITLE
Launching Dwarf Therapist fails if spaces in path

### ISSUE THREAD

**Issue by MikkoMMM** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#61]
When trying to launch Dwarf Therapist from Lazy Newb Pack, I got a popup saying:

> ERROR: not found.
> Verify $_DT_BINARY defined in /mnt/lvdata/games/linux/Dwarf
> /mnt/lvdata/games/linux/Dwarf Fortress LinuxLNP-0.44.12-r01/LNP/utilities/dwarf_therapist/Fortress
> /mnt/lvdata/games/linux/Dwarf Fortress LinuxLNP-0.44.12-r01/LNP/utilities/dwarf_therapist/LinuxLNP-0.44.12-r01/LNP/utilities/dwarf_therapist/launch.sh script is set correctly. 

And on the console:

> which: no dwarftherapist in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/mikko/opinnot/TIEP111)
> ERROR:  not found.
>         
> Verify $_DT_BINARY defined in /mnt/lvdata/games/linux/Dwarf
> /mnt/lvdata/games/linux/Dwarf Fortress LinuxLNP-0.44.12-r01/LNP/utilities/dwarf_therapist/Fortress
> /mnt/lvdata/games/linux/Dwarf Fortress LinuxLNP-0.44.12-r01/LNP/utilities/dwarf_therapist/LinuxLNP-0.44.12-r01/LNP/utilities/dwarf_therapist/launch.sh script is set correctly.
> 

After seeing the console log, I replaced the spaces with underscores in the file path. I can now successfully launch Dwarf Therapist from Lazy Newb Pack:

> 2018-Sep-22 17:33:14.104 INFO   core    Dwarf Therapist "40.1.2" starting normally. [src/dwarftherapist.cpp:181] (setup_logging)

**Comment by carterscottm** [comment]
Thank you for the report.  The source of this issue lies in the launch.sh script under LNP/dwarftherapist.  Adding double quotes around the $0 on line 37 will allow you to run Therapist with spaces in the path.  It should look like this:

```
CWD=`dirname "$(readlink -f "$0")"`

I'll make sure to update this on my end for the next revision.
