### ISSUE TITLE
Request: Pass command line flags given to startlnp on to PyLNP

### ISSUE THREAD

**Issue by puppable** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#62]
May be convenient for those who'd like to take advantage of PyLNP's command line flags. 

Should be as easy as adding a `$@` to the last line in the in the `startlnp` script as follows:
```sh
./PyLNP $@ || warn "Failed to start PyLNP"
```

**Comment by lethosor** [comment]
`"$@"` would be better to keep spaces intact

**Comment by carterscottm** [comment]
Easy enough!  Fixed in 69ad9dc.
