### ISSUE TITLE
gcc version used to compile dfhack in LNP

### ISSUE THREAD

**Issue by ragundo** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#65]
Hi there
I'm developing a dfhack plugin [dwarfexplorer](https://github.com/ragundo/DwarfExplorer).
I'm having problems with the deployment of the plugin in Linux using your LNP 

What gcc version do you use for compiling dfhack?. Is it 4.8? 5.3? 6?.

Also what glibc version do you use?.

The problem is with dfhack CoreSuspender. My plugin is compiled with gcc5.3 or gcc6 doesn't work with your dfhack.

I'll need to replicate your build settings in order to make my plugin compatible with the dfhack version that you provide with the LNP as I don't expect people to compile DFHack themselves.

Thanks

**Comment by lethosor** [comment]
From what I remember, it uses binaries distributed by DFHack. There were some CoreSuspender changes during 0.44.12, so make sure you're compiling with the right DFHack version. Also, what isn't working?

**Comment by ragundo** [comment]
@lethosor  https://github.com/cvuchener/dfhack-qt/issues

**Comment by lethosor** [comment]
My guess is the LNP is using the GCC 4.8 build, then.

**Comment by ragundo** [comment]
Yes. It's gcc4.8

Now it works
