### ISSUE TITLE
[Fedora 33 Linux] Dwarf Therapist refuses to lauch and core dumps

### ISSUE THREAD

**Issue by montaropdf** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#72]
Hello,

I have installed the LNP pack on a Fedora 33 machine, Dwarf Therapist refuses to start adn print the following in the terminal:

```
2021-mai-08 15:17:05.903 INFO   core    Dwarf Therapist "38.1.0" starting normally. [/home/scott/git/Dwarf-Therapist/src/dwarftherapist.cpp:186] (setup_logging)
2021-mai-08 15:17:05.903 INFO   core    Runtime QT Version 5.15.2 [/home/scott/git/Dwarf-Therapist/src/dwarftherapist.cpp:187] (setup_logging)
/home/roland/games/df-lnp/LinuxLNP-0.43.05-r07/LNP/utilities/dwarf_therapist/launch.sh : ligne 246 : 11580 Erreur de segmentation  (core dumped)${_SUDO} "${_DT_BINARY}"
```

Any idea what could be wrong?

**Comment by lethosor** [comment]
Does a standalone installation of DT from https://github.com/Dwarf-Therapist/Dwarf-Therapist have the same issue? (Note the instructions under the "Linux" section)

**Comment by montaropdf** [comment]
Hello @lethosor,

You can forget about this, it appears that I was not using the last version of the pack. With version 0.47.04, it works great.

Thanks for the suggestion, anyway.
