### ISSUE TITLE
Add GUI options to PyLNP to set its font properties

### ISSUE THREAD

**Issue by montaropdf** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#73]
Hello,

It would be really great to be able to select the font and its size (at least) of PyLNP. On linux, like others, I face an issue leading PyLNP to choose the tiniest font ever seen.

On a 42" screen, this is really eyes straining. Such feature could workaround such problem and ensure that users can adapt the application to their tastes and needs.

**Comment by lethosor** [comment]
This should probably be reported at https://github.com/Pidgeot/python-lnp instead - individual packs typically don't modify PyLNP itself

Edit: this might actually be a duplicate of https://github.com/Pidgeot/python-lnp/issues/176

**Comment by montaropdf** [comment]
> Edit: this might actually be a duplicate of [Pidgeot/python-lnp#176](https://github.com/Pidgeot/python-lnp/issues/176)

It seems so. 

I then close this issue and I will follow the one you mention.
